### ISSUE TITLE
Unknown props `wrapperStyle`, `parent` ...etc

### ISSUE THREAD

**Issue by borestad** [gatsbyjs/gatsby-starter-default#17]
This is a clean started project from this repository. Don't really know where to start.

![image](https://cloud.githubusercontent.com/assets/286455/16716656/80593b90-4703-11e6-833a-46fc055435ba.png)

**Comment by borestad** [comment]
Ah, noticed now that the bug belongs to https://github.com/KyleAMathews/react-headroom/pull/87

**Comment by KyleAMathews** [comment]
This is a new warning that's part of React 15.2.0. This particular warning needs fixed in React Headroom. There's an issue created for it already and I'll be fixing it soon https://github.com/KyleAMathews/react-headroom/issues/86.

In the meantime, there's actually nothing wrong atm, the React maintainers just added the warning as in the next major release, these extra props will cause errors.

**Comment by KyleAMathews** [comment]
ah, good find :-)
